import { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
  dir: 'rtl' | 'ltr';
}

const translations = {
  ar: {
    // Navigation
    'nav.dashboard': 'لوحة التحكم',
    'nav.projects': 'المشاريع',
    'nav.deliverables': 'شجرة المخرجات',
    'nav.consultants': 'إدارة المستشارين',
    'nav.clients': 'العملاء',
    'nav.tickets': 'التذاكر والطلبات',
    'nav.reports': 'التقارير والتحليلات',
    'nav.users': 'إدارة المستخدمين',
    'nav.settings': 'الإعدادات',
    'nav.meetings': 'الاجتماعات',
    'nav.communication': 'التواصل',
    'nav.logout': 'تسجيل الخروج',
    'nav.notifications': 'مركز الإشعارات',
    'nav.events': 'سجل الأحداث',
    'nav.assignments': 'إدارة التكليفات',
    'nav.rbac': 'الأدوار والصلاحيات',

    // Dashboard
    'dashboard.title': 'لوحة التحكم',
    'dashboard.welcome': 'مرحباً بك في منصة إدارة السياسات والإجراءات',
    'dashboard.totalProjects': 'إجمالي المشاريع',
    'dashboard.activeProjects': 'المشاريع النشطة',
    'dashboard.completedTasks': 'المهام المكتملة',
    'dashboard.pendingApprovals': 'الموافقات المعلقة',
    'dashboard.openTickets': 'التذاكر المفتوحة',
    'dashboard.recentProjects': 'المشاريع الحديثة',
    'dashboard.recentDeliverables': 'المخرجات الحديثة',
    'dashboard.recentTickets': 'التذاكر الحديثة',
    'dashboard.progress': 'التقدم',
    'dashboard.overallProgress': 'التقدم الإجمالي',
    'dashboard.projectsOverview': 'نظرة عامة على المشاريع',
    'dashboard.deliverablesOverview': 'نظرة عامة على المخرجات',
    'dashboard.teamPerformance': 'أداء الفريق',
    'dashboard.upcomingDeadlines': 'المواعيد النهائية القادمة',
    'dashboard.advanced.title': 'لوحة التحكم المتقدمة',
    'dashboard.advanced.overview': 'نظرة شاملة على المشاريع والمخرجات والاجتماعات',
    'dashboard.advanced.createNew': 'إنشاء جديد',
    'dashboard.advanced.projectStats': 'إحصائيات المشاريع',
    'dashboard.advanced.deliverableStats': 'إحصائيات المخرجات',
    'dashboard.advanced.meetingStats': 'إحصائيات الاجتماعات',
    'dashboard.advanced.recentActivity': 'النشاط الحديث',
    'dashboard.advanced.totalProjects': 'إجمالي المشاريع',
    'dashboard.advanced.activeProjects': 'مشاريع نشطة',
    'dashboard.advanced.completedProjects': 'مشاريع مكتملة',
    'dashboard.advanced.delayedProjects': 'مشاريع متأخرة',
    'dashboard.advanced.totalDeliverables': 'إجمالي المخرجات',
    'dashboard.advanced.pendingDeliverables': 'مخرجات معلقة',
    'dashboard.advanced.approvedDeliverables': 'مخرجات معتمدة',
    'dashboard.advanced.rejectedDeliverables': 'مخرجات مرفوضة',
    'dashboard.advanced.thisWeekMeetings': 'اجتماعات هذا الأسبوع',
    'dashboard.advanced.thisMonthMeetings': 'اجتماعات هذا الشهر',
    'dashboard.advanced.upcomingMeetings': 'اجتماعات قادمة',
    'dashboard.advanced.projectCompleted': 'تم إكمال المشروع',
    'dashboard.advanced.deliverablePending': 'مخرج في انتظار الاعتماد',
    'dashboard.advanced.meetingScheduled': 'اجتماع مجدول',
    'dashboard.advanced.newMessage': 'رسالة جديدة',
    'dashboard.advanced.uiDesignPhase1': 'تصميم واجهة المستخدم - المرحلة الأولى',
    'dashboard.advanced.weeklyReview': 'مراجعة التقدم الأسبوعي',
    'dashboard.advanced.devTeamUpdate': 'تحديث من فريق التطوير',
    'dashboard.advanced.loadDataError': 'فشل في تحميل بيانات لوحة التحكم',

    // Projects
    'projects.title': 'إدارة المشاريع',
    'projects.description': 'إدارة ومتابعة جميع المشاريع الاستشارية',
    'projects.newProject': 'مشروع جديد',
    'projects.search': 'البحث في المشاريع...',
    'projects.filterStatus': 'تصفية بالحالة',
    'projects.allStatuses': 'جميع الحالات',
    'projects.planning': 'تخطيط',
    'projects.active': 'نشط',
    'projects.onHold': 'معلق',
    'projects.completed': 'مكتمل',
    'projects.cancelled': 'ملغي',
    'projects.startDate': 'تاريخ البداية',
    'projects.endDate': 'تاريخ النهاية',
    'projects.budget': 'الميزانية',
    'projects.client': 'العميل',
    'projects.consultant': 'المستشار',
    'projects.view': 'عرض',
    'projects.edit': 'تحرير',
    'projects.team': 'الفريق',
    'projects.manage': 'إدارة المشروع',
    'projects.settings': 'إعدادات المشروع',
    'projects.duplicate': 'نسخ المشروع',
    'projects.archive': 'أرشفة',
    'projects.delete': 'حذف المشروع',
    'projects.overview': 'نظرة عامة',
    'projects.phases': 'المراحل',
    'projects.deliverables': 'المخرجات',
    'projects.timeline': 'الجدول الزمني',
    'projects.workflow': 'سير العمل',
    'projects.requirements': 'المتطلبات',
    'projects.meetings': 'الاجتماعات',
    'projects.communication': 'التواصل',
    'projects.audit': 'سجل العمليات',

    // Advanced Project Management
    'projects.advanced.title': 'إدارة المشاريع المتقدمة',
    'projects.advanced.phases': 'مراحل المشروع',
    'projects.advanced.deliverables': 'المخرجات',
    'projects.advanced.timeline': 'الجدول الزمني',
    'projects.advanced.progress': 'التقدم',
    'projects.advanced.analytics': 'التحليلات',
    'projects.advanced.audit_trail': 'سجل العمليات',
    'projects.advanced.requirements': 'المتطلبات الإلزامية',
    'projects.advanced.technical_proposal': 'العرض الفني',
    'projects.advanced.contract': 'العقد',
    'projects.advanced.project_charter': 'مخطط المشروع',
    'projects.advanced.activation': 'تفعيل المشروع',
    'projects.advanced.description': 'إدارة ومتابعة جميع المشاريع الاستشارية بشكل متقدم',
    'projects.advanced.searchProjects': 'البحث في المشاريع...',
    'projects.advanced.filterByStatus': 'تصفية بالحالة',
    'projects.advanced.filterByPriority': 'تصفية بالأولوية',
    'projects.advanced.allStatuses': 'جميع الحالات',
    'projects.advanced.allPriorities': 'جميع الأولويات',
    'projects.advanced.createProject': 'إنشاء مشروع جديد',
    'projects.advanced.projectName': 'اسم المشروع',
    'projects.advanced.projectDescription': 'وصف المشروع',
    'projects.advanced.projectStatus': 'حالة المشروع',
    'projects.advanced.projectPriority': 'أولوية المشروع',
    'projects.advanced.projectBudget': 'ميزانية المشروع',
    'projects.advanced.projectManager': 'مدير المشروع',
    'projects.advanced.projectClient': 'عميل المشروع',
    'projects.advanced.projectNameRequired': 'يجب إدخال اسم المشروع',
    'projects.advanced.projectCreated': 'تم إنشاء المشروع',
    'projects.advanced.projectCreatedDesc': 'تم إنشاء المشروع بنجاح',
    'projects.advanced.projectUpdated': 'تم تحديث المشروع',
    'projects.advanced.projectUpdatedDesc': 'تم تحديث المشروع بنجاح',
    'projects.advanced.projectDeleted': 'تم حذف المشروع',
    'projects.advanced.projectDeletedDesc': 'تم حذف المشروع بنجاح',
    'projects.advanced.confirmDelete': 'تأكيد الحذف',
    'projects.advanced.confirmDeleteDesc': 'هل أنت متأكد من حذف هذا المشروع؟ لا يمكن التراجع عن هذا الإجراء.',
    'projects.advanced.cancel': 'إلغاء',
    'projects.advanced.confirm': 'تأكيد',
    'projects.advanced.save': 'حفظ',
    'projects.advanced.edit': 'تحرير',
    'projects.advanced.delete': 'حذف',
    'projects.advanced.duplicate': 'نسخ',
    'projects.advanced.archive': 'أرشفة',
    'projects.advanced.backToProjects': 'العودة للمشاريع',
    'projects.advanced.projectManagement': 'إدارة المشروع',
    'projects.advanced.teamMembers': 'أعضاء الفريق',
    'projects.advanced.budget': 'الميزانية',
    'projects.advanced.spent': 'المصروف',
    'projects.advanced.remaining': 'المتبقي',
    'projects.advanced.lastActivity': 'آخر نشاط',
    'projects.advanced.noProjects': 'لا توجد مشاريع',
    'projects.advanced.noProjectsDesc': 'لم يتم العثور على مشاريع تطابق معايير البحث',
    'projects.advanced.contentManagementSystem': 'نظام إدارة المحتوى المتقدم',
    'projects.advanced.cmsDescription': 'تطوير نظام إدارة محتوى شامل مع واجهة مستخدم حديثة',
    'projects.advanced.ecommerceSystem': 'منصة التجارة الإلكترونية',
    'projects.advanced.ecommerceDescription': 'تطوير منصة تجارة إلكترونية متكاملة مع نظام دفع آمن',
    'projects.advanced.mobileApp': 'تطبيق الهاتف المحمول',
    'projects.advanced.mobileAppDescription': 'تطوير تطبيق محمول متعدد المنصات للخدمات المصرفية',
    'projects.advanced.tabs.overview': 'نظرة عامة',
    'projects.advanced.tabs.team': 'الفريق',
    'projects.advanced.tabs.deliverablesManagement': 'إدارة المخرجات',
    'projects.advanced.tabs.requirements': 'المتطلبات',
    'projects.advanced.tabs.phases': 'المراحل',
    'projects.advanced.tabs.deliverables': 'سير المخرجات',
    'projects.advanced.tabs.meetings': 'الاجتماعات',
    'projects.advanced.tabs.communication': 'التواصل',
    'projects.advanced.tabs.audit': 'سجل العمليات',
    'projects.advanced.completedPhases': 'المراحل المكتملة',
    'projects.advanced.currentPhase': 'المرحلة الحالية',
    'projects.advanced.projectProgress': 'تقدم المشروع',
    'projects.advanced.projectDetails': 'تفاصيل المشروع',
    'projects.advanced.projectInfo': 'معلومات المشروع',
    'projects.advanced.team': 'الفريق',
    'projects.advanced.manager': 'المدير',
    'projects.advanced.currentPhaseLabel': 'المرحلة الحالية',
    'projects.advanced.lastActivityLabel': 'آخر نشاط',
    'projects.advanced.tabs.reviews': 'المراجعات',

    // Tree System
    'tree.projectTree': 'شجرة المشروع',
    'tree.phasesTree': 'شجرة المراحل',
    'tree.deliverablesTree': 'شجرة المخرجات',
    'tree.expandAll': 'توسيع الكل',
    'tree.collapseAll': 'طي الكل',
    'tree.refresh': 'تحديث',
    'tree.loading': 'جاري التحميل...',
    'tree.error': 'خطأ في تحميل بيانات الشجرة',
    'tree.noData': 'لا توجد بيانات متاحة',
    
    // Phases
    'phases.title': 'مراحل المشروع',
    'phases.createPhase': 'إنشاء مرحلة',
    'phases.editPhase': 'تحرير المرحلة',
    'phases.deletePhase': 'حذف المرحلة',
    'phases.phaseName': 'اسم المرحلة',
    'phases.description': 'الوصف',
    'phases.startDate': 'تاريخ البداية',
    'phases.endDate': 'تاريخ النهاية',
    'phases.activities': 'الأنشطة',
    'phases.createActivity': 'إنشاء نشاط',
    'phases.noActivities': 'لا توجد أنشطة في هذه المرحلة',
    
    // Activities
    'activities.title': 'الأنشطة',
    'activities.createActivity': 'إنشاء نشاط',
    'activities.editActivity': 'تحرير النشاط',
    'activities.deleteActivity': 'حذف النشاط',
    'activities.activityName': 'اسم النشاط',
    'activities.owner': 'المسؤول',
    'activities.progress': 'التقدم',
    'activities.status': 'الحالة',
    'activities.plannedDates': 'التواريخ المخططة',
    'activities.actualDates': 'التواريخ الفعلية',
    
    // Activity Status
    'activities.status.notStarted': 'لم يبدأ',
    'activities.status.inProgress': 'قيد التنفيذ',
    'activities.status.done': 'مكتمل',
    'activities.status.blocked': 'محجوب',
    
    // Deliverables Tree
    'deliverablesTree.title': 'شجرة المخرجات',
    'deliverablesTree.createDeliverable': 'إنشاء مخرج',
    'deliverablesTree.editDeliverable': 'تحرير المخرج',
    'deliverablesTree.deleteDeliverable': 'حذف المخرج',
    'deliverablesTree.deliverableName': 'اسم المخرج',
    'deliverablesTree.weight': 'الوزن',
    'deliverablesTree.weightUnit': 'وحدة الوزن',
    'deliverablesTree.percent': 'نسبة مئوية',
    'deliverablesTree.points': 'نقاط',
    'deliverablesTree.parts': 'الأجزاء',
    'deliverablesTree.createPart': 'إنشاء جزء',
    'deliverablesTree.noParts': 'لا توجد أجزاء في هذا المخرج',
    'deliverablesTree.finalFile': 'الملف النهائي',
    'deliverablesTree.uploadFinal': 'رفع الملف النهائي',
    
    // Assignments
    'assignments.title': 'التكليفات',
    'assignments.createAssignment': 'إنشاء تكليف',
    'assignments.assignee': 'المكلف',
    'assignments.deliverable': 'المخرج',
    'assignments.part': 'الجزء',
    'assignments.permissions': 'الصلاحيات',
    'assignments.canUpload': 'يمكن الرفع',
    'assignments.canSubmit': 'يمكن التسليم',
    'assignments.canRespond': 'يمكن الرد',
    'assignments.notify': 'إشعار',
    'assignments.message': 'الرسالة',
    
    // Grants
    'grants.title': 'منح الوصول',
    'grants.createGrant': 'إنشاء منحة',
    'grants.grantee': 'المستفيد',
    'grants.accessLevel': 'مستوى الوصول',
    'grants.view': 'عرض',
    'grants.comment': 'تعليق',
    'grants.review': 'مراجعة',
    'grants.approve': 'موافقة',
    'grants.expiresAt': 'تنتهي في',
    
    // File Management
    'files.title': 'إدارة الملفات',
    'files.upload': 'رفع ملف',
    'files.download': 'تحميل',
    'files.fileName': 'اسم الملف',
    'files.fileSize': 'حجم الملف',
    'files.uploadedAt': 'تاريخ الرفع',
    'files.version': 'الإصدار',
    'files.versions': 'الإصدارات',
    'files.notes': 'ملاحظات',
    'files.selectFile': 'اختر ملف',
    
    // Progress
    'progress.title': 'التقدم',
    'progress.overall': 'التقدم الإجمالي',
    'progress.weighted': 'التقدم المرجح',
    'progress.completed': 'مكتمل',
    'progress.remaining': 'متبقي',
    'progress.behindSchedule': 'متأخر عن الجدول',
    'progress.onTrack': 'في المسار الصحيح',

    // Deliverables
    'deliverables.title': 'شجرة المخرجات',
    'deliverables.description': 'إدارة وتنظيم جميع الأدلة والسياسات والإجراءات',
    'deliverables.newDeliverable': 'مخرج جديد',
    'deliverables.uploadFile': 'رفع ملف',
    'deliverables.search': 'البحث في المخرجات...',
    'deliverables.expandAll': 'توسيع الكل',
    'deliverables.collapseAll': 'طي الكل',
    'deliverables.guide': 'دليل',
    'deliverables.topic': 'موضوع',
    'deliverables.policy': 'سياسة',
    'deliverables.procedure': 'إجراء',
    'deliverables.template': 'قالب',
    'deliverables.draft': 'مسودة',
    'deliverables.review': 'مراجعة',
    'deliverables.approved': 'معتمد',
    'deliverables.published': 'منشور',
    'deliverables.version': 'الإصدار',
    'deliverables.project': 'المشروع',
    'deliverables.management': 'إدارة المخرجات',
    'deliverables.versions': 'إدارة الإصدارات',
    'deliverables.reviews': 'المراجعات',
    'deliverables.submitForReview': 'إرسال للمراجعة',

    // Deliverables Status
    'deliverables.status.not_started': 'لم يبدأ',
    'deliverables.status.in_progress': 'قيد التنفيذ',
    'deliverables.status.submitted': 'مرفوع للمراجعة',
    'deliverables.status.under_review': 'قيد المراجعة',
    'deliverables.status.changes_requested': 'طلب تعديلات',
    'deliverables.status.approved': 'معتمد',
    'deliverables.status.closed': 'مغلق',

    // Clients
    'clients.title': 'إدارة العملاء',
    'clients.description': 'قاعدة بيانات العملاء والمشاريع المرتبطة',
    'clients.newClient': 'عميل جديد',
    'clients.search': 'البحث في العملاء...',
    'clients.organization': 'المؤسسة',
    'clients.contactPerson': 'الشخص المسؤول',
    'clients.email': 'البريد الإلكتروني',
    'clients.phone': 'الهاتف',
    'clients.activeProjects': 'المشاريع النشطة',
    'clients.totalProjects': 'إجمالي المشاريع',

    // Tickets
    'tickets.title': 'نظام التذاكر والطلبات',
    'tickets.description': 'إدارة ومتابعة جميع طلبات التحديث والاستفسارات',
    'tickets.newTicket': 'تذكرة جديدة',
    'tickets.search': 'البحث في التذاكر...',
    'tickets.filterPriority': 'تصفية بالأولوية',
    'tickets.allPriorities': 'جميع الأولويات',
    'tickets.low': 'منخفضة',
    'tickets.medium': 'متوسطة',
    'tickets.high': 'عالية',
    'tickets.urgent': 'عاجلة',
    'tickets.open': 'مفتوح',
    'tickets.inProgress': 'قيد المعالجة',
    'tickets.waitingResponse': 'في انتظار الرد',
    'tickets.resolved': 'محلول',
    'tickets.closed': 'مغلق',
    'tickets.category': 'الفئة',
    'tickets.dueDate': 'الموعد النهائي',
    'tickets.createdAt': 'تاريخ الإنشاء',

    // Reports
    'reports.title': 'التقارير والتحليلات',
    'reports.description': 'تحليلات شاملة لأداء المشاريع والمخرجات',
    'reports.projectsOverview': 'نظرة عامة على المشاريع',
    'reports.deliverablesStatus': 'حالة المخرجات',
    'reports.clientSatisfaction': 'رضا العملاء',
    'reports.performanceMetrics': 'مؤشرات الأداء',

    // User Roles
    'roles.system_admin': 'مدير النظام',
    'roles.project_manager': 'مدير المشروع',
    'roles.project_consultant': 'مستشار المشروع',
    'roles.lead_consultant': 'المستشار الرئيسي',
    'roles.sub_consultant': 'المستشار المساعد',
    'roles.main_client': 'العميل الرئيسي',
    'roles.sub_client': 'العميل الفرعي',

    // Meetings
    'meetings.title': 'إدارة الاجتماعات',
    'meetings.new_meeting': 'اجتماع جديد',
    'meetings.agenda': 'جدول الأعمال',
    'meetings.attendees': 'الحضور',
    'meetings.minutes': 'محضر الاجتماع',
    'meetings.decisions': 'القرارات',
    'meetings.recommendations': 'التوصيات',
    'meetings.schedule': 'جدولة اجتماع',
    'meetings.join': 'انضمام للاجتماع',
    'meetings.status.scheduled': 'مجدول',
    'meetings.status.ongoing': 'جاري',
    'meetings.status.completed': 'مكتمل',
    'meetings.status.cancelled': 'ملغي',

    // Communication
    'communication.title': 'التواصل الداخلي',
    'communication.messages': 'الرسائل',
    'communication.conversations': 'المحادثات',
    'communication.send_message': 'إرسال رسالة',
    'communication.new_conversation': 'محادثة جديدة',
    'communication.compose': 'كتابة رسالة',
    'communication.channels': 'القنوات',
    'communication.notifications': 'الإشعارات',

    // Notifications
    'notifications.title': 'مركز الإشعارات',
    'notifications.markAllRead': 'تحديد الكل كمقروء',
    'notifications.events': 'الأحداث',
    'notifications.unread': 'غير مقروء',
    'notifications.read': 'مقروء',



    // RBAC
    'rbac.title': 'الأدوار والصلاحيات',
    'rbac.roles': 'الأدوار',
    'rbac.permissions': 'الصلاحيات',
    'rbac.assignments': 'التخصيصات',
    'rbac.audit': 'سجل التغييرات',
    'rbac.addAssignment': 'إضافة تخصيص جديد',

    // User Management
    'users.title': 'إدارة المستخدمين',
    'users.registrationRequests': 'طلبات التسجيل',
    'users.userProfiles': 'ملفات المستخدمين',
    'users.invitations': 'الدعوات',
    'users.activityLog': 'سجل النشاط',
    'users.createUser': 'إنشاء مستخدم جديد',
    'users.approve': 'اعتماد',
    'users.reject': 'رفض',
    'users.resendInvitation': 'إعادة إرسال الدعوة',

    // Common
    'common.loading': 'جاري التحميل...',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تحرير',
    'common.view': 'عرض',
    'common.download': 'تحميل',
    'common.upload': 'رفع',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.refresh': 'تحديث',
    'common.export': 'تصدير',
    'common.import': 'استيراد',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.confirm': 'تأكيد',
    'common.status': 'الحالة',
    'common.priority': 'الأولوية',
    'common.date': 'التاريخ',
    'common.time': 'الوقت',
    'common.description': 'الوصف',
    'common.title': 'العنوان',
    'common.name': 'الاسم',
    'common.type': 'النوع',
    'common.actions': 'الإجراءات',
    'common.add': 'إضافة',
    'common.create': 'إنشاء',
    'common.update': 'تحديث',
    'common.close': 'إغلاق',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.submit': 'إرسال',
    'common.reset': 'إعادة تعيين',
    'common.clear': 'مسح',
    'common.select': 'اختيار',
    'common.all': 'الكل',
    'common.none': 'لا شيء',

    // Auth
    'auth.signIn': 'تسجيل الدخول',
    'auth.signUp': 'إنشاء حساب',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.confirmPassword': 'تأكيد كلمة المرور',
    'auth.fullName': 'الاسم الكامل',
    'auth.role': 'الدور',
    'auth.selectRole': 'اختر الدور',
    'auth.forgotPassword': 'نسيت كلمة المرور؟',
    'auth.alreadyHaveAccount': 'لديك حساب بالفعل؟',
    'auth.dontHaveAccount': 'ليس لديك حساب؟',
    'auth.organization': 'المؤسسة',
    'auth.phone': 'رقم الهاتف',
    'auth.requestSignup': 'طلب تسجيل',
    'auth.registrationReason': 'سبب طلب التسجيل',

    // Forms
    'form.required': 'مطلوب',
    'form.optional': 'اختياري',
    'form.selectOption': 'اختر خيار',
    'form.enterText': 'أدخل النص',
    'form.chooseFile': 'اختر ملف',
    'form.dragDropFile': 'اسحب وأفلت الملف هنا',

    // Messages
    'message.success': 'تم بنجاح',
    'message.error': 'حدث خطأ',
    'message.warning': 'تحذير',
    'message.info': 'معلومات',
    'message.confirmDelete': 'هل أنت متأكد من الحذف؟',
    'message.noData': 'لا توجد بيانات',
    'message.accessDenied': 'غير مصرح',
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.projects': 'Projects',
    'nav.deliverables': 'Deliverables Tree',
    'nav.consultants': 'Consultants Management',
    'nav.clients': 'Clients',
    'nav.tickets': 'Tickets & Requests',
    'nav.reports': 'Reports & Analytics',
    'nav.users': 'User Management',
    'nav.settings': 'Settings',
    'nav.meetings': 'Meetings',
    'nav.communication': 'Communication',
    'nav.logout': 'Logout',
    'nav.notifications': 'Notification Center',
    'nav.events': 'Events Log',
    'nav.assignments': 'Assignments Management',
    'nav.rbac': 'Roles & Permissions',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome to Policies & Procedures Management Platform',
    'dashboard.totalProjects': 'Total Projects',
    'dashboard.activeProjects': 'Active Projects',
    'dashboard.completedTasks': 'Completed Tasks',
    'dashboard.pendingApprovals': 'Pending Approvals',
    'dashboard.openTickets': 'Open Tickets',
    'dashboard.recentProjects': 'Recent Projects',
    'dashboard.recentDeliverables': 'Recent Deliverables',
    'dashboard.recentTickets': 'Recent Tickets',
    'dashboard.progress': 'Progress',
    'dashboard.overallProgress': 'Overall Progress',
    'dashboard.projectsOverview': 'Projects Overview',
    'dashboard.deliverablesOverview': 'Deliverables Overview',
    'dashboard.teamPerformance': 'Team Performance',
    'dashboard.upcomingDeadlines': 'Upcoming Deadlines',
    'dashboard.advanced.title': 'Advanced Dashboard',
    'dashboard.advanced.overview': 'Comprehensive overview of projects, deliverables, and meetings',
    'dashboard.advanced.createNew': 'Create New',
    'dashboard.advanced.projectStats': 'Project Statistics',
    'dashboard.advanced.deliverableStats': 'Deliverable Statistics',
    'dashboard.advanced.meetingStats': 'Meeting Statistics',
    'dashboard.advanced.recentActivity': 'Recent Activity',
    'dashboard.advanced.totalProjects': 'Total Projects',
    'dashboard.advanced.activeProjects': 'Active Projects',
    'dashboard.advanced.completedProjects': 'Completed Projects',
    'dashboard.advanced.delayedProjects': 'Delayed Projects',
    'dashboard.advanced.totalDeliverables': 'Total Deliverables',
    'dashboard.advanced.pendingDeliverables': 'Pending Deliverables',
    'dashboard.advanced.approvedDeliverables': 'Approved Deliverables',
    'dashboard.advanced.rejectedDeliverables': 'Rejected Deliverables',
    'dashboard.advanced.thisWeekMeetings': 'This Week Meetings',
    'dashboard.advanced.thisMonthMeetings': 'This Month Meetings',
    'dashboard.advanced.upcomingMeetings': 'Upcoming Meetings',
    'dashboard.advanced.projectCompleted': 'Project Completed',
    'dashboard.advanced.deliverablePending': 'Deliverable Pending Approval',
    'dashboard.advanced.meetingScheduled': 'Meeting Scheduled',
    'dashboard.advanced.newMessage': 'New Message',
    'dashboard.advanced.uiDesignPhase1': 'UI Design - Phase 1',
    'dashboard.advanced.weeklyReview': 'Weekly Progress Review',
    'dashboard.advanced.devTeamUpdate': 'Development Team Update',
    'dashboard.advanced.loadDataError': 'Failed to load dashboard data',

    // Projects
    'projects.title': 'Project Management',
    'projects.description': 'Manage and track all consulting projects',
    'projects.newProject': 'New Project',
    'projects.search': 'Search projects...',
    'projects.filterStatus': 'Filter by Status',
    'projects.allStatuses': 'All Statuses',
    'projects.planning': 'Planning',
    'projects.active': 'Active',
    'projects.onHold': 'On Hold',
    'projects.completed': 'Completed',
    'projects.cancelled': 'Cancelled',
    'projects.startDate': 'Start Date',
    'projects.endDate': 'End Date',
    'projects.budget': 'Budget',
    'projects.client': 'Client',
    'projects.consultant': 'Consultant',
    'projects.view': 'View',
    'projects.edit': 'Edit',
    'projects.team': 'Team',
    'projects.manage': 'Manage Project',
    'projects.settings': 'Project Settings',
    'projects.duplicate': 'Duplicate Project',
    'projects.archive': 'Archive',
    'projects.delete': 'Delete Project',
    'projects.overview': 'Overview',
    'projects.phases': 'Phases',
    'projects.deliverables': 'Deliverables',
    'projects.timeline': 'Timeline',
    'projects.workflow': 'Workflow',
    'projects.requirements': 'Requirements',
    'projects.meetings': 'Meetings',
    'projects.communication': 'Communication',
    'projects.audit': 'Audit Trail',

    // Advanced Project Management
    'projects.advanced.title': 'Advanced Project Management',
    'projects.advanced.phases': 'Project Phases',
    'projects.advanced.deliverables': 'Deliverables',
    'projects.advanced.timeline': 'Timeline',
    'projects.advanced.progress': 'Progress',
    'projects.advanced.analytics': 'Analytics',
    'projects.advanced.audit_trail': 'Audit Trail',
    'projects.advanced.requirements': 'Mandatory Requirements',
    'projects.advanced.technical_proposal': 'Technical Proposal',
    'projects.advanced.contract': 'Contract',
    'projects.advanced.project_charter': 'Project Charter',
    'projects.advanced.activation': 'Project Activation',
    'projects.advanced.description': 'Manage and track all consulting projects in an advanced way',
    'projects.advanced.searchProjects': 'Search projects...',
    'projects.advanced.filterByStatus': 'Filter by Status',
    'projects.advanced.filterByPriority': 'Filter by Priority',
    'projects.advanced.allStatuses': 'All Statuses',
    'projects.advanced.allPriorities': 'All Priorities',
    'projects.advanced.createProject': 'Create New Project',
    'projects.advanced.projectName': 'Project Name',
    'projects.advanced.projectDescription': 'Project Description',
    'projects.advanced.projectStatus': 'Project Status',
    'projects.advanced.projectPriority': 'Project Priority',
    'projects.advanced.projectBudget': 'Project Budget',
    'projects.advanced.projectManager': 'Project Manager',
    'projects.advanced.projectClient': 'Project Client',
    'projects.advanced.projectNameRequired': 'Project name is required',
    'projects.advanced.projectCreated': 'Project Created',
    'projects.advanced.projectCreatedDesc': 'Project created successfully',
    'projects.advanced.projectUpdated': 'Project Updated',
    'projects.advanced.projectUpdatedDesc': 'Project updated successfully',
    'projects.advanced.projectDeleted': 'Project Deleted',
    'projects.advanced.projectDeletedDesc': 'Project deleted successfully',
    'projects.advanced.confirmDelete': 'Confirm Delete',
    'projects.advanced.confirmDeleteDesc': 'Are you sure you want to delete this project? This action cannot be undone.',
    'projects.advanced.cancel': 'Cancel',
    'projects.advanced.confirm': 'Confirm',
    'projects.advanced.save': 'Save',
    'projects.advanced.edit': 'Edit',
    'projects.advanced.delete': 'Delete',
    'projects.advanced.duplicate': 'Duplicate',
    'projects.advanced.archive': 'Archive',
    'projects.advanced.backToProjects': 'Back to Projects',
    'projects.advanced.projectManagement': 'Project Management',
    'projects.advanced.teamMembers': 'Team Members',
    'projects.advanced.budget': 'Budget',
    'projects.advanced.spent': 'Spent',
    'projects.advanced.remaining': 'Remaining',
    'projects.advanced.lastActivity': 'Last Activity',
    'projects.advanced.noProjects': 'No Projects',
    'projects.advanced.noProjectsDesc': 'No projects found matching the search criteria',
    'projects.advanced.contentManagementSystem': 'Advanced Content Management System',
    'projects.advanced.cmsDescription': 'Develop a comprehensive content management system with modern user interface',
    'projects.advanced.ecommerceSystem': 'E-commerce Platform',
    'projects.advanced.ecommerceDescription': 'Develop an integrated e-commerce platform with secure payment system',
    'projects.advanced.mobileApp': 'Mobile Application',
    'projects.advanced.mobileAppDescription': 'Develop a cross-platform mobile application for banking services',
    'projects.advanced.tabs.overview': 'Overview',
    'projects.advanced.tabs.team': 'Team',
    'projects.advanced.tabs.deliverablesManagement': 'Deliverables Management',
    'projects.advanced.tabs.requirements': 'Requirements',
    'projects.advanced.tabs.phases': 'Phases',
    'projects.advanced.tabs.deliverables': 'Deliverables Workflow',
    'projects.advanced.tabs.meetings': 'Meetings',
    'projects.advanced.tabs.communication': 'Communication',
    'projects.advanced.tabs.audit': 'Audit Trail',
    'projects.advanced.completedPhases': 'Completed Phases',
    'projects.advanced.currentPhase': 'Current Phase',
    'projects.advanced.projectProgress': 'Project Progress',
    'projects.advanced.projectDetails': 'Project Details',
    'projects.advanced.projectInfo': 'Project Information',
    'projects.advanced.team': 'Team',
    'projects.advanced.manager': 'Manager',
    'projects.advanced.currentPhaseLabel': 'Current Phase',
    'projects.advanced.lastActivityLabel': 'Last Activity',
    'projects.advanced.tabs.reviews': 'Reviews',

    // Deliverables
    'deliverables.title': 'Deliverables Tree',
    'deliverables.description': 'Manage and organize all guides, policies, and procedures',
    'deliverables.newDeliverable': 'New Deliverable',
    'deliverables.uploadFile': 'Upload File',
    'deliverables.search': 'Search deliverables...',
    'deliverables.expandAll': 'Expand All',
    'deliverables.collapseAll': 'Collapse All',
    'deliverables.guide': 'Guide',
    'deliverables.topic': 'Topic',
    'deliverables.policy': 'Policy',
    'deliverables.procedure': 'Procedure',
    'deliverables.template': 'Template',
    'deliverables.draft': 'Draft',
    'deliverables.review': 'Review',
    'deliverables.approved': 'Approved',
    'deliverables.published': 'Published',
    'deliverables.version': 'Version',
    'deliverables.project': 'Project',
    'deliverables.management': 'Deliverables Management',
    'deliverables.versions': 'Version Management',
    'deliverables.reviews': 'Reviews',
    'deliverables.submitForReview': 'Submit for Review',

    // Tree System
    'tree.projectTree': 'Project Tree',
    'tree.phasesTree': 'Phases Tree',
    'tree.deliverablesTree': 'Deliverables Tree',
    'tree.expandAll': 'Expand All',
    'tree.collapseAll': 'Collapse All',
    'tree.refresh': 'Refresh',
    'tree.loading': 'Loading...',
    'tree.error': 'Error loading tree data',
    'tree.noData': 'No data available',
    
    // Phases
    'phases.title': 'Project Phases',
    'phases.createPhase': 'Create Phase',
    'phases.editPhase': 'Edit Phase',
    'phases.deletePhase': 'Delete Phase',
    'phases.phaseName': 'Phase Name',
    'phases.description': 'Description',
    'phases.startDate': 'Start Date',
    'phases.endDate': 'End Date',
    'phases.activities': 'Activities',
    'phases.createActivity': 'Create Activity',
    'phases.noActivities': 'No activities in this phase',
    
    // Activities
    'activities.title': 'Activities',
    'activities.createActivity': 'Create Activity',
    'activities.editActivity': 'Edit Activity',
    'activities.deleteActivity': 'Delete Activity',
    'activities.activityName': 'Activity Name',
    'activities.owner': 'Owner',
    'activities.progress': 'Progress',
    'activities.status': 'Status',
    'activities.plannedDates': 'Planned Dates',
    'activities.actualDates': 'Actual Dates',
    
    // Activity Status
    'activities.status.notStarted': 'Not Started',
    'activities.status.inProgress': 'In Progress',
    'activities.status.done': 'Done',
    'activities.status.blocked': 'Blocked',
    
    // Deliverables Tree
    'deliverablesTree.title': 'Deliverables Tree',
    'deliverablesTree.createDeliverable': 'Create Deliverable',
    'deliverablesTree.editDeliverable': 'Edit Deliverable',
    'deliverablesTree.deleteDeliverable': 'Delete Deliverable',
    'deliverablesTree.deliverableName': 'Deliverable Name',
    'deliverablesTree.weight': 'Weight',
    'deliverablesTree.weightUnit': 'Weight Unit',
    'deliverablesTree.percent': 'Percent',
    'deliverablesTree.points': 'Points',
    'deliverablesTree.parts': 'Parts',
    'deliverablesTree.createPart': 'Create Part',
    'deliverablesTree.noParts': 'No parts in this deliverable',
    'deliverablesTree.finalFile': 'Final File',
    'deliverablesTree.uploadFinal': 'Upload Final File',
    
    // Assignments
    'assignments.title': 'Assignments',
    'assignments.createAssignment': 'Create Assignment',
    'assignments.assignee': 'Assignee',
    'assignments.deliverable': 'Deliverable',
    'assignments.part': 'Part',
    'assignments.permissions': 'Permissions',
    'assignments.canUpload': 'Can Upload',
    'assignments.canSubmit': 'Can Submit',
    'assignments.canRespond': 'Can Respond',
    'assignments.notify': 'Notify',
    'assignments.message': 'Message',
    
    // Grants
    'grants.title': 'Access Grants',
    'grants.createGrant': 'Create Grant',
    'grants.grantee': 'Grantee',
    'grants.accessLevel': 'Access Level',
    'grants.view': 'View',
    'grants.comment': 'Comment',
    'grants.review': 'Review',
    'grants.approve': 'Approve',
    'grants.expiresAt': 'Expires At',
    
    // File Management
    'files.title': 'File Management',
    'files.upload': 'Upload File',
    'files.download': 'Download',
    'files.fileName': 'File Name',
    'files.fileSize': 'File Size',
    'files.uploadedAt': 'Uploaded At',
    'files.version': 'Version',
    'files.versions': 'Versions',
    'files.notes': 'Notes',
    'files.selectFile': 'Select File',
    
    // Progress
    'progress.title': 'Progress',
    'progress.overall': 'Overall Progress',
    'progress.weighted': 'Weighted Progress',
    'progress.completed': 'Completed',
    'progress.remaining': 'Remaining',
    'progress.behindSchedule': 'Behind Schedule',
    'progress.onTrack': 'On Track',

    // Deliverables Status
    'deliverables.status.not_started': 'Not Started',
    'deliverables.status.in_progress': 'In Progress',
    'deliverables.status.submitted': 'Submitted for Review',
    'deliverables.status.under_review': 'Under Review',
    'deliverables.status.changes_requested': 'Changes Requested',
    'deliverables.status.approved': 'Approved',
    'deliverables.status.closed': 'Closed',

    // Clients
    'clients.title': 'Client Management',
    'clients.description': 'Client database and associated projects',
    'clients.newClient': 'New Client',
    'clients.search': 'Search clients...',
    'clients.organization': 'Organization',
    'clients.contactPerson': 'Contact Person',
    'clients.email': 'Email',
    'clients.phone': 'Phone',
    'clients.activeProjects': 'Active Projects',
    'clients.totalProjects': 'Total Projects',

    // Tickets
    'tickets.title': 'Tickets & Requests System',
    'tickets.description': 'Manage and track all update requests and inquiries',
    'tickets.newTicket': 'New Ticket',
    'tickets.search': 'Search tickets...',
    'tickets.filterPriority': 'Filter by Priority',
    'tickets.allPriorities': 'All Priorities',
    'tickets.low': 'Low',
    'tickets.medium': 'Medium',
    'tickets.high': 'High',
    'tickets.urgent': 'Urgent',
    'tickets.open': 'Open',
    'tickets.inProgress': 'In Progress',
    'tickets.waitingResponse': 'Waiting Response',
    'tickets.resolved': 'Resolved',
    'tickets.closed': 'Closed',
    'tickets.category': 'Category',
    'tickets.dueDate': 'Due Date',
    'tickets.createdAt': 'Created At',

    // Reports
    'reports.title': 'Reports & Analytics',
    'reports.description': 'Comprehensive analytics for project and deliverable performance',
    'reports.projectsOverview': 'Projects Overview',
    'reports.deliverablesStatus': 'Deliverables Status',
    'reports.clientSatisfaction': 'Client Satisfaction',
    'reports.performanceMetrics': 'Performance Metrics',

    // User Roles
    'roles.system_admin': 'System Administrator',
    'roles.project_manager': 'Project Manager',
    'roles.project_consultant': 'Project Consultant',
    'roles.lead_consultant': 'Lead Consultant',
    'roles.sub_consultant': 'Sub-Consultant',
    'roles.main_client': 'Main Client',
    'roles.sub_client': 'Sub-Client',

    // Meetings
    'meetings.title': 'Meetings Management',
    'meetings.new_meeting': 'New Meeting',
    'meetings.agenda': 'Agenda',
    'meetings.attendees': 'Attendees',
    'meetings.minutes': 'Meeting Minutes',
    'meetings.decisions': 'Decisions',
    'meetings.recommendations': 'Recommendations',
    'meetings.schedule': 'Schedule Meeting',
    'meetings.join': 'Join Meeting',
    'meetings.status.scheduled': 'Scheduled',
    'meetings.status.ongoing': 'Ongoing',
    'meetings.status.completed': 'Completed',
    'meetings.status.cancelled': 'Cancelled',

    // Communication
    'communication.title': 'Internal Communication',
    'communication.messages': 'Messages',
    'communication.conversations': 'Conversations',
    'communication.send_message': 'Send Message',
    'communication.new_conversation': 'New Conversation',
    'communication.compose': 'Compose Message',
    'communication.channels': 'Channels',
    'communication.notifications': 'Notifications',

    // Notifications
    'notifications.title': 'Notification Center',
    'notifications.markAllRead': 'Mark All as Read',
    'notifications.events': 'Events',
    'notifications.unread': 'Unread',
    'notifications.read': 'Read',



    // RBAC
    'rbac.title': 'Roles & Permissions',
    'rbac.roles': 'Roles',
    'rbac.permissions': 'Permissions',
    'rbac.assignments': 'Assignments',
    'rbac.audit': 'Audit Log',
    'rbac.addAssignment': 'Add New Assignment',

    // User Management
    'users.title': 'User Management',
    'users.registrationRequests': 'Registration Requests',
    'users.userProfiles': 'User Profiles',
    'users.invitations': 'Invitations',
    'users.activityLog': 'Activity Log',
    'users.createUser': 'Create New User',
    'users.approve': 'Approve',
    'users.reject': 'Reject',
    'users.resendInvitation': 'Resend Invitation',

    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.refresh': 'Refresh',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.confirm': 'Confirm',
    'common.status': 'Status',
    'common.priority': 'Priority',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.description': 'Description',
    'common.title': 'Title',
    'common.name': 'Name',
    'common.type': 'Type',
    'common.actions': 'Actions',
    'common.add': 'Add',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.submit': 'Submit',
    'common.reset': 'Reset',
    'common.clear': 'Clear',
    'common.select': 'Select',
    'common.all': 'All',
    'common.none': 'None',

    // Auth
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.fullName': 'Full Name',
    'auth.role': 'Role',
    'auth.selectRole': 'Select Role',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.dontHaveAccount': "Don't have an account?",
    'auth.organization': 'Organization',
    'auth.phone': 'Phone Number',
    'auth.requestSignup': 'Request Signup',
    'auth.registrationReason': 'Registration Reason',

    // Forms
    'form.required': 'Required',
    'form.optional': 'Optional',
    'form.selectOption': 'Select Option',
    'form.enterText': 'Enter Text',
    'form.chooseFile': 'Choose File',
    'form.dragDropFile': 'Drag and drop file here',

    // Messages
    'message.success': 'Success',
    'message.error': 'Error Occurred',
    'message.warning': 'Warning',
    'message.info': 'Information',
    'message.confirmDelete': 'Are you sure you want to delete?',
    'message.noData': 'No Data Available',
    'message.accessDenied': 'Access Denied',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('ar');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'ar' || savedLanguage === 'en')) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    
    // Update body class for styling
    document.body.className = document.body.className.replace(/\b(rtl|ltr)\b/g, '');
    document.body.classList.add(lang === 'ar' ? 'rtl' : 'ltr');
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  const toggleLanguage = () => {
    const newLang = language === 'ar' ? 'en' : 'ar';
    handleSetLanguage(newLang);
  };

  const value = {
    language,
    setLanguage: handleSetLanguage,
    toggleLanguage,
    t,
    dir: language === 'ar' ? 'rtl' as const : 'ltr' as const,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}