-- ربط الأدوار بالصلاحيات - الجزء الأول

-- صلاحيات مدير النظام (SYSTEM_ADMIN) - جميع الصلاحيات
-- مدير النظام له صلاحية "*" أي جميع الصلاحيات
INSERT INTO public.rbac_role_permissions_2025_12_16_11_00 (role_code, permission_code) 
SELECT 'SYSTEM_ADMIN', code FROM public.rbac_permissions_2025_12_16_11_00;

-- صلاحيات مدير المشروع (PROJECT_MANAGER)
INSERT INTO public.rbac_role_permissions_2025_12_16_11_00 (role_code, permission_code) VALUES 
-- إدارة النظام (محدودة)
('PROJECT_MANAGER', 'ORG_READ'),
('PROJECT_MANAGER', 'USER_READ'),
('PROJECT_MANAGER', 'ROLE_READ'),
('PROJECT_MANAGER', 'PERMISSION_READ'),

-- إدارة العملاء (قراءة فقط)
('PROJECT_MANAGER', 'CLIENT_READ'),
('PROJECT_MANAGER', 'CLIENT_USER_READ'),

-- إدارة المشاريع (كاملة)
('PROJECT_MANAGER', 'PROJECT_READ'),
('PROJECT_MANAGER', 'PROJECT_UPDATE'),
('PROJECT_MANAGER', 'PROJECT_ACTIVATE'),
('PROJECT_MANAGER', 'PROJECT_CLOSE'),
('PROJECT_MANAGER', 'PROJECT_MEMBERS_READ'),
('PROJECT_MANAGER', 'PROJECT_MEMBER_ADD'),
('PROJECT_MANAGER', 'PROJECT_MEMBER_UPDATE'),
('PROJECT_MANAGER', 'PROJECT_MEMBER_REMOVE'),
('PROJECT_MANAGER', 'PROJECT_TIMELINE_UPDATE'),
('PROJECT_MANAGER', 'PROJECT_PHASE_INIT_DEFAULT'),
('PROJECT_MANAGER', 'PROJECT_PHASE_READ'),
('PROJECT_MANAGER', 'PROJECT_PHASE_UPDATE'),
('PROJECT_MANAGER', 'PROJECT_DOCUMENT_UPLOAD'),
('PROJECT_MANAGER', 'PROJECT_DOCUMENT_READ'),
('PROJECT_MANAGER', 'PROJECT_DOCUMENT_DELETE'),

-- إدارة المخرجات (كاملة)
('PROJECT_MANAGER', 'DELIVERABLE_CREATE'),
('PROJECT_MANAGER', 'DELIVERABLE_READ'),
('PROJECT_MANAGER', 'DELIVERABLE_UPDATE'),
('PROJECT_MANAGER', 'DELIVERABLE_STATUS_UPDATE'),
('PROJECT_MANAGER', 'DELIVERABLE_WEIGHT_UPDATE'),
('PROJECT_MANAGER', 'DELIVERABLE_ASSIGN_CREATE'),
('PROJECT_MANAGER', 'DELIVERABLE_ASSIGN_READ'),
('PROJECT_MANAGER', 'DELIVERABLE_ASSIGN_UPDATE'),
('PROJECT_MANAGER', 'DELIVERABLE_ASSIGN_DELETE'),

-- إدارة الإصدارات (قراءة فقط)
('PROJECT_MANAGER', 'DELIVERABLE_VERSION_READ'),

-- سير عمل المراجعة
('PROJECT_MANAGER', 'DELIVERABLE_SUBMIT_FOR_REVIEW'),
('PROJECT_MANAGER', 'REVIEW_READ'),

-- طلبات إعادة الفتح
('PROJECT_MANAGER', 'REOPEN_REQUEST_READ'),
('PROJECT_MANAGER', 'REOPEN_REQUEST_DECIDE'),

-- منح الوصول (كاملة)
('PROJECT_MANAGER', 'GRANT_CREATE'),
('PROJECT_MANAGER', 'GRANT_READ'),
('PROJECT_MANAGER', 'GRANT_UPDATE'),
('PROJECT_MANAGER', 'GRANT_DELETE'),

-- الرسائل (كاملة مع صلاحية خاصة)
('PROJECT_MANAGER', 'MESSAGE_READ'),
('PROJECT_MANAGER', 'MESSAGE_SEND'),
('PROJECT_MANAGER', 'MESSAGE_PM_VIEW_ALL'),

-- الاجتماعات (كاملة)
('PROJECT_MANAGER', 'MEETING_CREATE'),
('PROJECT_MANAGER', 'MEETING_READ'),
('PROJECT_MANAGER', 'MEETING_UPDATE'),
('PROJECT_MANAGER', 'MEETING_DELETE'),
('PROJECT_MANAGER', 'MINUTES_CREATE'),
('PROJECT_MANAGER', 'MINUTES_READ'),
('PROJECT_MANAGER', 'DECISION_CREATE'),
('PROJECT_MANAGER', 'DECISION_UPDATE'),
('PROJECT_MANAGER', 'DECISION_READ'),

-- التقارير والتدقيق (كاملة)
('PROJECT_MANAGER', 'REPORT_PROJECT_STATUS_READ'),
('PROJECT_MANAGER', 'REPORT_TIMELINE_READ'),
('PROJECT_MANAGER', 'REPORT_DELIVERABLES_READ'),
('PROJECT_MANAGER', 'REPORT_CLIENT_DELAYS_READ'),
('PROJECT_MANAGER', 'AUDIT_LOG_READ'),
('PROJECT_MANAGER', 'AUDIT_LOG_EXPORT'),

-- إدارة الملفات
('PROJECT_MANAGER', 'FILE_PRESIGN_CREATE');